// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: NodePack/node.proto

package NodePack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoIntoCrit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoIntoCrit string `protobuf:"bytes,1,opt,name=goIntoCrit,proto3" json:"goIntoCrit,omitempty"`
}

func (x *GoIntoCrit) Reset() {
	*x = GoIntoCrit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoIntoCrit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoIntoCrit) ProtoMessage() {}

func (x *GoIntoCrit) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoIntoCrit.ProtoReflect.Descriptor instead.
func (*GoIntoCrit) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{0}
}

func (x *GoIntoCrit) GetGoIntoCrit() string {
	if x != nil {
		return x.GoIntoCrit
	}
	return ""
}

type ServerDoneInCrit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerDoneInCrit string `protobuf:"bytes,1,opt,name=serverDoneInCrit,proto3" json:"serverDoneInCrit,omitempty"`
}

func (x *ServerDoneInCrit) Reset() {
	*x = ServerDoneInCrit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerDoneInCrit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDoneInCrit) ProtoMessage() {}

func (x *ServerDoneInCrit) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDoneInCrit.ProtoReflect.Descriptor instead.
func (*ServerDoneInCrit) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{1}
}

func (x *ServerDoneInCrit) GetServerDoneInCrit() string {
	if x != nil {
		return x.ServerDoneInCrit
	}
	return ""
}

type RequestPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeid int32 `protobuf:"varint,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
}

func (x *RequestPermission) Reset() {
	*x = RequestPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPermission) ProtoMessage() {}

func (x *RequestPermission) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPermission.ProtoReflect.Descriptor instead.
func (*RequestPermission) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPermission) GetNodeid() int32 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

type GivePermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GivePermission string `protobuf:"bytes,1,opt,name=givePermission,proto3" json:"givePermission,omitempty"`
}

func (x *GivePermission) Reset() {
	*x = GivePermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GivePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivePermission) ProtoMessage() {}

func (x *GivePermission) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivePermission.ProtoReflect.Descriptor instead.
func (*GivePermission) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{3}
}

func (x *GivePermission) GetGivePermission() string {
	if x != nil {
		return x.GivePermission
	}
	return ""
}

type ReleaseToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeid int32 `protobuf:"varint,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
}

func (x *ReleaseToken) Reset() {
	*x = ReleaseToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseToken) ProtoMessage() {}

func (x *ReleaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseToken.ProtoReflect.Descriptor instead.
func (*ReleaseToken) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseToken) GetNodeid() int32 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodePack_node_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_NodePack_node_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_NodePack_node_proto_rawDescGZIP(), []int{5}
}

var File_NodePack_node_proto protoreflect.FileDescriptor

var file_NodePack_node_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2c, 0x0a, 0x0a, 0x47,
	0x6f, 0x49, 0x6e, 0x74, 0x6f, 0x43, 0x72, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x49,
	0x6e, 0x74, 0x6f, 0x43, 0x72, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x6f, 0x49, 0x6e, 0x74, 0x6f, 0x43, 0x72, 0x69, 0x74, 0x22, 0x3e, 0x0a, 0x10, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x12, 0x2a, 0x0a,
	0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44,
	0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x69, 0x76, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x69, 0x76, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x67, 0x69, 0x76, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x26, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0xa7, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x43, 0x72, 0x69, 0x74, 0x12, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x6f, 0x49, 0x6e,
	0x74, 0x6f, 0x43, 0x72, 0x69, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x12, 0x2b,
	0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x43, 0x72, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x0b,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x68,
	0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x57, 0x65, 0x72, 0x65, 0x6e, 0x66, 0x65, 0x6c, 0x64, 0x74, 0x2f, 0x44, 0x69, 0x73,
	0x79, 0x73, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x32, 0x2f, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_NodePack_node_proto_rawDescOnce sync.Once
	file_NodePack_node_proto_rawDescData = file_NodePack_node_proto_rawDesc
)

func file_NodePack_node_proto_rawDescGZIP() []byte {
	file_NodePack_node_proto_rawDescOnce.Do(func() {
		file_NodePack_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_NodePack_node_proto_rawDescData)
	})
	return file_NodePack_node_proto_rawDescData
}

var file_NodePack_node_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_NodePack_node_proto_goTypes = []interface{}{
	(*GoIntoCrit)(nil),        // 0: main.GoIntoCrit
	(*ServerDoneInCrit)(nil),  // 1: main.ServerDoneInCrit
	(*RequestPermission)(nil), // 2: main.RequestPermission
	(*GivePermission)(nil),    // 3: main.GivePermission
	(*ReleaseToken)(nil),      // 4: main.ReleaseToken
	(*Empty)(nil),             // 5: main.Empty
}
var file_NodePack_node_proto_depIdxs = []int32{
	2, // 0: main.Node.Permission:input_type -> main.RequestPermission
	0, // 1: main.Node.AccesCrit:input_type -> main.GoIntoCrit
	4, // 2: main.Node.ExitCrit:input_type -> main.ReleaseToken
	3, // 3: main.Node.Permission:output_type -> main.GivePermission
	1, // 4: main.Node.AccesCrit:output_type -> main.ServerDoneInCrit
	5, // 5: main.Node.ExitCrit:output_type -> main.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NodePack_node_proto_init() }
func file_NodePack_node_proto_init() {
	if File_NodePack_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_NodePack_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoIntoCrit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodePack_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerDoneInCrit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodePack_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodePack_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GivePermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodePack_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodePack_node_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NodePack_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_NodePack_node_proto_goTypes,
		DependencyIndexes: file_NodePack_node_proto_depIdxs,
		MessageInfos:      file_NodePack_node_proto_msgTypes,
	}.Build()
	File_NodePack_node_proto = out.File
	file_NodePack_node_proto_rawDesc = nil
	file_NodePack_node_proto_goTypes = nil
	file_NodePack_node_proto_depIdxs = nil
}
